# Generated by Django 3.2.19 on 2023-11-04 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20230530_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='tipo',
            new_name='categoria',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='produtos',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(default='descricao', max_length=500),
        ),
        migrations.AddField(
            model_name='produtos',
            name='preco',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='produtos',
            name='tamanho',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
